### PR TITLE
Fix for images not showing in Directory

### PR DESCRIPTION
**Pull request by donnapep**

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees There appear to be problems when setting table border to `collapse`. Apparently it needs to be `separate` or the header column widths are incorrectly calculated by the dataTables plugin. So instead I set it to `collapse` after the table has been configured.

Please review. Thx.

**Comment by stulees** [comment]
@donnapep Okay makes sense :+1:

**Comment by donnapep** [comment]
@stulees Please review latest commit. Thx.

**Comment by stulees** [comment]
@donnapep I think the gadget code needs to check the refresh value is no less than 300 and force it to 300 if need be.

**Comment by donnapep** [comment]
@stulees That's not what I understood from Alan's comment. Let me double check.

**Comment by stulees** [comment]
@donnapep Have seen Alan's comment on Trello, based on we're just applying a default value - :+1:

**Pull request closed without merging**
