### PR TITLE
Use getValue in combination with parseFloat

### PR DESCRIPTION
**Pull request by donnapep**
`getFormattedValue` returns a comma now, which means `parseFloat` returns an incorrect value. Use `getValue` instead.

### CODE REVIEW

**Comment by donnapep** [comment]
@stulees @rodrigopavezi Please review. Thx.

**Comment by rodrigopavezi** [comment]
@donnapep looks good 👍 cheers

**Comment by stulees** [comment]
@donnapep Is `getFormattedValue` providing anything `getValue` can't that might be required for displaying? Just wondering if changing to use `getValue` is going to be detrimental. If so, maybe remove the `,` from the value obtained by `getFormattedValue` first and then `parseFloat` that value.

**Comment by donnapep** [comment]
@stulees I don't believe so. There's actually an `addCommas` function in the code to add those commas in for display purposes. But here it's being used in calculations so `getValue` is the more appropriate choice.

**Comment by stulees** [comment]
@donnapep Okay thanks 👍

**Comment by donnapep** [comment]
@stulees You might have to deploy this tomorrow. You can just overwrite `FinancialChart.js` and `FinancialChart.min.js` in the `Gadget-Financial-Chart` bucket. I would take a backup of the existing files first though just in case. Thx.

**Pull request merged**
