### PR TITLE
Correct minified version of Directory JS

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep The previous version of `directory.min.js` did not seem to be the right current version. I have now minified exactly what is recent from `directory.js`.

**Comment by donnapep** [comment]
@stulees Sorry, but do you mean that you minified the copy from the master branch of Github? Or you minified the copy from the `Gadget-Directory-Test` bucket?

**Comment by stulees** [comment]
@donnapep This change is for minifying (using an online minifier) the `directory.js` from master. You had previously committed a version in your PR before this, but the look of the minification seemed different to how this one is and I thought it might have coincided with the fact that Mat was not able to validate the fix on all machines/channels. It hasn't seemed to make a difference as this minified file in this PR is currently on production.

**Comment by donnapep** [comment]
@stulees I think the difference is just in the different minifiers that we used. We should get this merged though since it's what's currently in Production. :+1:

**Pull request merged**
