### PR TITLE
Use fixed viz version

### PR DESCRIPTION
**Pull request by alex-deaconu**
Version 48 in unminified file allows
dates to be in new Date format

Version 47 for the minified file
which does not include the previous fix

Tested both changes locally with the Charles proxy.

As per https://developers.google.com/chart/interactive/docs/release_notes#current:-july-2020 the dates correspond with when the 2 issues with the library started happening.

### CODE REVIEW

**Comment by alex-deaconu** [comment]
@ezequielc @olegrise please review. Thanks!

**Comment by olegrise** [comment]
@alex-deaconu good idea re. locking the version number. 
Re. minified file - if it works, I'm good with it.

**Comment by alex-deaconu** [comment]
Smoke tested release and Validated on a Display by Support.

**Comment by alex-deaconu** [comment]
Fix https://github.com/Rise-Vision/gadgets/issues/45

**Pull request merged**
